Move comment and ignore exit codes

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -50,16 +50,20 @@ jobs:
         pip install spinegeneric@git+https://github.com/spine-generic/spine-generic.git@v2.9
 
     - name: Run bids-validator
+      # I would prefer to whitelist the allowed environment variables,
+      # but upstream adds new ones unpredictably. At least we don't
+      # allow any network access.
       run: |
-        # I would prefer to whitelist the allowed environment variables,
-        # but upstream adds new ones unpredictably. At least we don't
-        # allow any network access.
         deno run --no-prompt --allow-env --allow-read=. jsr:@bids/validator .
 
     - name: Run acquisition parameter validator
+      # we ignore the exit code because we expect warnings, but we still want
+      # to see them
       run: |
-        sg_params_checker -path-in .
+        sg_params_checker -path-in . || true
 
     - name: Run data consistency validator
+      # we ignore the exit code because we expect warnings, but we still want
+      # to see them
       run: |
-        sg_check_data_consistency -path-in .
+        sg_check_data_consistency -path-in . || true
